/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface JsRendererConfig {
  name: string
  moduleName: string
  elements: Array<string>
}

/** Transform options exposed to JavaScript */
export interface JsTransformOptions {
  /**
   * The module to import runtime helpers from
   * @default "solid-js/web"
   */
  moduleName?: string
  /** Multi-renderer configuration used by `generate: "dynamic"` */
  renderers?: Array<JsRendererConfig>
  /**
   * Generate mode: "dom", "ssr", "universal", or "dynamic"
   * @default "dom"
   */
  generate?: string
  /**
   * Whether to enable hydration support
   * @default false
   */
  hydratable?: boolean
  /**
   * Whether to delegate events
   * @default true
   */
  delegateEvents?: boolean
  /**
   * Whether to wrap conditionals
   * @default true
   */
  wrapConditionals?: boolean
  /**
   * Whether nested closing tags may be omitted in template output
   * @default false
   */
  omitNestedClosingTags?: boolean
  /**
   * Whether the last closing tag may be omitted in template output
   * @default true
   */
  omitLastClosingTag?: boolean
  /**
   * Whether static attributes may omit quotes when safe
   * @default true
   */
  omitQuotes?: boolean
  /**
   * Whether static styles may be inlined into template HTML
   * @default true
   */
  inlineStyles?: boolean
  /**
   * Whether to pass context to custom elements
   * @default true
   */
  contextToCustomElements?: boolean
  /**
   * Source filename
   * @default "input.jsx"
   */
  filename?: string
  /**
   * Whether to generate source maps
   * @default false
   */
  sourceMap?: boolean
  /**
   * Only transform files containing a matching `@jsxImportSource <value>` comment
   * @default undefined
   */
  requireImportSource?: string
  /**
   * Whether to validate generated HTML templates for browser rewrites
   * @default true
   */
  validate?: boolean
  /**
   * Enable HMR (solid-refresh) transform
   * @default false
   */
  hmr?: boolean
  /**
   * HMR bundler type: "esm", "vite", "standard", "webpack5", "rspack-esm"
   * @default "standard"
   */
  hmrBundler?: string
  /**
   * Enable granular HMR (dependency tracking + signatures)
   * @default true
   */
  hmrGranular?: boolean
  /**
   * Enable JSX expression extraction for HMR
   * @default true
   */
  hmrJsx?: boolean
  /**
   * Fix render() calls for HMR (wrap with cleanup + dispose)
   * @default true
   */
  hmrFixRender?: boolean
}

/** Transform JSX source code */
export declare function transformJsx(source: string, options?: JsTransformOptions | undefined | null): TransformResult

/** Result of a transform operation */
export interface TransformResult {
  /** The transformed code */
  code: string
  /** Source map (if enabled) */
  map?: string
}
